name: gds

on:
  workflow_dispatch:
  push:
    # Don't run on project submissions:
    branches-ignore:
      - projects/tt_um_*
  pull_request:
    # Don't run on project submissions:
    paths-ignore:
      - projects/tt_um_*/**

jobs:
  gds:
    env:
      FOUNDRY_ID: TT2603
      PYTHONIOENCODING: utf-8
      PDK: ihp-sg13g2
      PDK_ROOT: ${{ github.workspace }}/IHP-Open-PDK
      TT_CONFIG: ihp-sg13g2.yaml
      # Uncomment the following line to build only the specified projects:
      #TT_ONLY_PROJECTS: tt_um_chip_rom,tt_um_factory_test

    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
          docker-images: false
          swap-storage: false
          android: false

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r tt-multiplexer/py/requirements.txt -r tt/requirements.txt -r verilog/dv/mux/requirements.txt

      - name: Update caravel configuration
        run: python ./tt/configure.py --update-shuttle

      - name: Install Nix and configure FOSSi cache
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://nix-cache.fossi-foundation.org
            extra-trusted-public-keys = nix-cache.fossi-foundation.org:3+K59iFwXqKsL7BNu6Guy0v+uTlwsxYQxjspXzqLYQs=

      - name: Harden Chip ROM
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python -m librelane --pdk-root $PDK_ROOT --manual-pdk --pdk $PDK tt/rom/config.json"

      - name: Harden tt_ctrl
        working-directory: tt-multiplexer/ol2/tt_ctrl
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python build.py"

      - name: Harden tt_mux
        working-directory: tt-multiplexer/ol2/tt_mux
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python build.py"

      - name: Copy macros
        run: python ./tt/configure.py --copy-macros

      - name: Harden tt_top
        working-directory: tt-multiplexer/ol2/tt_top
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python build.py"

      - name: Copy final results
        run: python ./tt/configure.py --copy-final-results

      - name: Create foundry submission directory
        run: python ./tt/configure.py --create-foundry-submission

      - name: upload GDS artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: GDS
          path: tt-multiplexer/ol2/tt_top/runs/RUN_*/*

      - name: upload macros artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: macros
          path: |
            tt-multiplexer/cfg/*.yaml
            tt-multiplexer/ol2/tt_top/gds/*
            tt-multiplexer/ol2/tt_top/lef/*
            tt-multiplexer/ol2/tt_top/spef/*
            tt-multiplexer/ol2/tt_top/verilog/*
            tt-multiplexer/ol2/tt_mux/runs/RUN_*/*
            tt-multiplexer/ol2/tt_ctrl/runs/RUN_*/*

      - name: upload shuttle_index.json
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: shuttle_index
          path: shuttle_index.json

      - name: Install KLayout
        shell: bash
        run: |
          wget https://github.com/TinyTapeout/klayout/releases/download/v0.29.12/klayout_0.29.12-1_amd64.deb
          sudo apt-get update && sudo apt-get install -y ./klayout_0.29.12-1_amd64.deb

      - name: Generate fill and add logo
        working-directory: fill
        run: |
          export SYSTEM_PYTHON=$(which python3)
          nix profile install nixpkgs#magic-vlsi
          nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "make fill KLAYOUT_CMD=/usr/bin/klayout SYSTEM_PYTHON=$SYSTEM_PYTHON -j2"

      - name: Rename top-level cell for IHP submission, convert to OAS
        run: |
          python fill/rename.py foundry_submission/gds/tt_ihp_wrapper_final.gds foundry_submission/gds/$FOUNDRY_ID.gds $FOUNDRY_ID
          strm2oas foundry_submission/gds/$FOUNDRY_ID.gds foundry_submission/gds/$FOUNDRY_ID.oas

      - name: upload foundry submission directory
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: foundry_submission
          path: foundry_submission

      - name: Install iverilog (for GL simulation)
        run: |
          wget https://github.com/TinyTapeout/iverilog/releases/download/13.0-git-d8c3c51/iverilog_13.0-git-d8c3c51a-1_amd64.deb
          sudo apt-get update -y
          sudo apt-get install -y ./iverilog_13.0-git-d8c3c51a-1_amd64.deb

      - name: GL simulation
        working-directory: verilog/dv/mux
        env:
          EXPECTED_REPO: ${{ github.repository }}
        run: |
          # temporary workaround for missing bits in pad_raw:
          sed -i 's/inout \[61:0\] pad_raw/inout [63:0] pad_raw/' ../../../foundry_submission/verilog/gl/tt_ihp_wrapper.nl.v

          make clean test_mux_gl
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: upload GL test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: gl_test_vcd
          path: |
            verilog/dv/mux/results.xml
            verilog/dv/mux/test_mux.vcd
            verilog/dv/mux/test_mux.gtkw
